# Generated by Django 5.1.6 on 2025-02-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicerequest_is_provider_selected'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='service_provided',
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='service_provided',
            field=models.ManyToManyField(related_name='service_provided', to='services.servicecategory'),
        ),
    ]
