# Generated by Django 5.1.6 on 2025-02-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_tenantprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantprofile',
            name='maintenance_preferences',
            field=models.TextField(blank=True),
        ),
    ]
