# Generated by Django 5.1.6 on 2025-02-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereview',
            name='provider',
        ),
    ]
