# Generated by Django 5.1.6 on 2025-02-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='is_provider_selected',
            field=models.BooleanField(default=False),
        ),
    ]
