# Generated by Django 5.1.6 on 2025-02-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicerequest_is_provider_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='category',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='category',
            field=models.ManyToManyField(related_name='service_requests', to='services.servicecategory'),
        ),
    ]
